#!/bin/bash
pubkey=This needs to be the public key of the STM
privkey=This needs to be the LONG private key as generated by repclient --gentemp
fetchkey=This is the SHORT private key as generated by repclient --genkey --hidden=true --sync==true
basedir=Full absolute directory for STM, including trailing slash. Needs to have children: input/ and stm/
server=Full URL for the server to use for index fetch and posts
startID=0

echo Pubkey: ${pubkey}
while true; do

startID=$[ $(cat ${basedir}/last.id) + 0 ]
echo Fetch from ${startID}

last=$(repclient --index --server ${server} --outdir ${basedir}/input --privkey ${fetchkey} --start ${startID} --count 30 --appdata 2>&1 | grep MessageList | cut -d\: -f2- | cut -d\  -f1 | tail -n1)

if [ -n "${last}" ]; then
	if [ ${last} -gt 0 ]; then
		echo New message $(date)
		echo $last > ${basedir}/last.id
	fi
else
	echo No message $(date)
fi

for inMsg in $(ls ${basedir}/input); do
	repclient --decrypt --in ${basedir}/input/${inMsg} --stmdir ${basedir}/stm/ --privkey ${privkey} > /dev/null && rm ${basedir}/input/${inMsg}
done

repclient --stm --stmdir ${basedir}/stm/ --verbose --server ${server}

sleep 300s
done
